language: python
python: '2.7'
install: python build_rules.py
script: python -m unittest test_build_rules
deploy:
  provider: releases
  api_key:
    secure: TbheycLAIcn1JGetIAPFPsKakYH2dIe/ZDdM/eU9gPutMemGFQdnpIlMfjUE0XyM9v0BuiLCLNO5hV7V5MXqGyFHvy1G0QpfavryR2hOihP+fzGVXWVFWBKmzW0B6u0XmUeKc8rl1jqY5CoQhVPEVGyBIA/6QzudgCJf+egQN/hDS39Cd3HLw34MKVKwnXcAYZGSNSqBk0jURMrHUqgP+mfPlAqNUnT4xLiMbXZnU9+TFGw7IcunSkwmGsA446iVQwITfJHkBTD1L/zEm6D4aqwIXyphpv6meJdz+hafnlEY7iMR8s9T1JOFIUcrliougf/fcibfIh+ta6eBq5vxxApSft7xF1j/t/M15U2byQaOxwx3AEqcUl79SojZF1VuB67PI+PgDOHXR1JPX6UrjqWZx7OoeTqLScaWdqK/UaEtFCVw+rTTCJmb/dQ6XlQe9hs7dF00+336rwohAjLg9fiw4e9poot9R1bxxExENoH067VIrNM8y56TEjg6GeSZRiLn5udWtE8NMbtrXXHD0VOusYe6M5ToajLUsQOoKiMuno0Ca9X/B+kBd4W2uiIWPTEh8tUBgaNvTzKLnt7Kq1P5TiPPmEYN0mxoNSHOdJbQcMKjfStTdUnDeqmyC78DBZu8GeLDMUyA9jIZnxeuMPLJB43JT6FSDNSLxaqKBAM=
  file:
    - hosts.txt
    - domains.txt
  on:
    repo: ndfred/unifi-pi-hole
