language: python
python: '2.7'
install: python build_rules.py
script: python -m unittest test_build_rules
deploy:
  provider: releases
  api_key:
    secure: pObxjDCF1nR0ghJ4Ud3SImy2f3PCoykv2sFhp1a7/XvItigWj9PuB43Vmb2dA5phj+kM8pztUl3OqhDQBbvMOEM2vlfIJWHnpodVDe31krAcJdSuShyPkAXPnnWPkbeyIGH7zQ8xDwhhpzG/ts28LTWxVlAMNyrKwPN/mXRNpwChZaFYdwh2dPr6nxMB7l3ae4PGglQ20WsgrFypnQemAdLSNvQfqIuqHOWkPlyfZuOPCKgKvMjrzXKCsh8W6H6yn6i8reODyhZVFdyxY8oMQePDqCne8uJ/mxAgpnIPI0A7kH9x1hIc7Fcq7ppfWgy/ZLeBhW6CENOAaex4CKAoHm32X7u8eg12jaZRQvlINKF01bYv3c7U18uQKwCbKEGXZkgmOCWTcb1nCtbaAI3Ma7zO9zzSuzeZ/S3u7ktI6+rhEg+UFD4Ir6LMfoTx+Qfl1vLGb1PNfz6J7pkdalNrPec/nip8I8NMF+zoyHt6SKE5vj8rqXWG31ZEt/hDlhI9BzZs7flBDmePBRWaaYY1ry1UbhgH0U0OFOtSPsG0Gixp9C/VaCzGjDDmZ97dBT5zVCLbYL/33JCDYnpuZnz0QOYOfD32tZEHO3gD3ZjFwkUzSheLL+iPfeaok78N5S0DZ8TAQnwUoNBfqZ2rFHxr7lNpeneJlu2LRWkVQnVoWjM=
  file:
    - hosts.txt
    - domains.txt
  on:
    repo: ndfred/unifi-pi-hole
